version: '3.3'

services:
  adapter:
    image: 127.0.0.1:5001/iot-adapter
    build: iot-adapter/
#    env_file:
#      - .env
    networks:
      - iot-adapter
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 4G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


# Network
networks:
  iot-adapter:
